# src/Resources/config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Charge tous les services du bundle (controllers, services, twig, etc.)
  Djdmg\TransparentPixelBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Resources,Tests}'

  # (Optionnel: autoconfigure tag automatiquement si la classe étend \Twig\Extension\AbstractExtension)
  Djdmg\TransparentPixelBundle\Twig\PixelExtension:
    tags: ['twig.extension']

  # (Optionnel) Controllers: utile si tu veux forcer le tag controller.service_arguments
  Djdmg\TransparentPixelBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']